# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4190dea46ac2673d43c3b106f6fba5e6e97d71580b96f19666509cbd38dee19bf07f6f5a49c4d5834fe9e9779c8ad002bbb97d8c446cbb2e9b503c50e412ac48

test:
  secret_key_base: 5fa3b9d2d5010a2a80f1f07b8e17e22281a8aefa146d532e06afface1f280980f97e052c1fb4da764780f305c0013525ebb0095007971e735c60d48a91fc8ce8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
