# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb340a7e4461b01dc73182d795291862d88c4b3a88cb0f518afecc170fa15a3e771726e39ea63ac8b5b4b95c56a7ca4f85d7d42167bccbbf36f3ecb3d298b6d2

test:
  secret_key_base: 8b5e3e748994bc15302596417a6d620477ed70f295c9afb7f3bb786dd5a84cedc7d811830fcbd491f7835a5f9c9ff5c2848313bf24d46a6fae0a309ffefa59ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
